pgdumper:
  name: pg-dumper
  image: cr.yandex/crpn9ikb6hp5v19o9957/pgdumper
  version: 60
  envs:
    - PG_HOST
    - PG_PASSWORD
    - PG_USER
    - PG_DATABASE
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_BUCKET_NAME
    - AWS_HOST
    - AWS_PORT
pgrestore:
  name: pg-restore
  image: cr.yandex/crpn9ikb6hp5v19o9957/pgrestore
  version: 15
  envs:
    - PG_HOST
    - PG_PASSWORD
    - PG_USER
    - PG_DATABASE
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_BUCKET_NAME
    - AWS_HOST
    - AWS_PORT
app:
  name: inf-app
  image: cr.yandex/crpn9ikb6hp5v19o9957/inf-frontend-dev
  version: "31"
  components: frontend
  port: 3000
  replicas: 1
  requests:
    cpu: "250m"
    memory: "250Mi"
  limits:
    cpu: "250m"
    memory: "250Mi"
  envs:
    - EXTERNAL_CATALOG_SERVER_URL
    - API_SERVER_URL
api:
  name: inf-api
  image: cr.yandex/crpn9ikb6hp5v19o9957/inf-backend-dev
  version: "7"
  components: backend
  port: 2348
  replicas: 1
  requests:
    cpu: "500m"
    memory: "350Mi"
  limits:
    cpu: "500m"
    memory: "350Mi"
  envs:
    - CLIENT_URL
    - DB_PORT
    - DB_HOST
    - REDIS_URL
postgres:
  name: postgres
  image: postgres
  version: 14
  replicas: 1
  components: postgres
  port: 5432
  requests:
    cpu: "1000m"
    memory: "2000Mi"
  limits:
    cpu: "1000m"
    memory: "2000Mi"
  envs:
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
redis:
  name: redis
  image: redis
  version: 7.0.7
  replicas: 1
  components: redis
  port: 6379
  requests:
    cpu: "200m"
    memory: "250Mi"
  limits:
    cpu: "200m"
    memory: "250Mi"
database:
  db: inf
  user: postgres
  password: postgres
vault:
  secret_id_app: "13f4b2fb-9dd8-0938-adec-35b7f31ff25a"
  secret_id_api: "8b2f3d1f-d5ab-5ddb-2d66-521c63593544"
  secret_id_postgres: "772e0968-1829-87a6-cc61-baca8d472bd6"
  secret_id_s3: "bf1d0c91-b6e1-06e6-6d96-574957f97074"
  all_role_id: "4288f0ba-d77f-c280-8bae-20e3dc837b99"
  server_ip: "http://10.96.187.248:8200"
