apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.global.app.name }}-clusterip"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.app.port }}
      protocol: TCP
  selector:
    components: {{ .Values.global.app.components }}