apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-app
  annotations:
      nginx.ingress.kubernetes.io/base-url: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: infinitum.test
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: "{{ .Values.global.app.name }}-clusterip"
            port: 
              number: {{ .Values.global.app.port }}