apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : fullstack-short-service
  namespace: argocd-inf
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: app
  source:
    repoURL: git@github.com:jakkaru-devops/inf-argocd.git
    path   : HelmCharts/Development
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true         