apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : fullstack-short-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: inf-application-dev
  source:
    repoURL: git@github.com:jakkaru-devops/inf-argocd.git
    path   : HelmCharts/Development
    targetRevision: HEAD
    # helm:
    #   valueFiles:
    #   - values.yaml
    #   parameters:
    #   - name: "app.version"
    #     value: d345f43355c71033e4a46d435a4cab76b76a9cfb
    #   - name: "api.version"
    #     value: ec1d8da9d1fae61692d750d1234f4fa7dc44044f
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    
   
