apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: api-dr
  namespace: {{ .Values.namespace.istio }}
spec:
  host: "{{ .Values.api.name }}-clusterip"
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: "api-vs"
#   namespace: {{ .Values.namespace.istio }}
# spec:
#   gateways:
#   - app-gateway
#   hosts:
#   - infinitum.test
#   http:
#   - match:
#       - uri:
#           prefix: /api
#       - uri:
#           prefix: /api/v2
#     route:
#     - destination:
#         host: "{{ .Values.api.name }}-clusterip"
#         subset: v1
#         port:
#           number: {{ .Values.api.port }}
#       weight: 50
#     - destination:
#         host: "{{ .Values.api.name }}-clusterip"
#         subset: v2
#         port:
#           number: {{ .Values.api.port }}
#       weight: 50
