apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.api.name }}-clusterip"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      protocol: TCP
  selector:
    app: {{ .Values.api.name }}