apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: app-dr
  namespace: {{ .Values.namespace.istio }}
spec:
  host: "{{ .Values.app.name }}-clusterip"
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "app-vs"
  namespace: {{ .Values.namespace.istio }}
spec:
  gateways:
  - app-gateway
  hosts:
  - infinitum.test
  http:
  - match:
      - uri:
          prefix: /
    route:
    - destination:
        host: "{{ .Values.app.name }}-clusterip"
        subset: v1
        port:
          number: {{ .Values.app.port }}
      weight: 50
    - destination:
        host: "{{ .Values.app.name }}-clusterip"
        subset: v2
        port:
          number: {{ .Values.app.port }}
      weight: 50
      
      
