apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.redis.name }}-clusterip"
  namespace: {{ .Values.namespace.istio }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      protocol: TCP
  selector:
    components: {{ .Values.redis.components }}