pgdumper:
  name: pg-dumper
  image: cr.yandex/crpn9ikb6hp5v19o9957/pgdumper
  version: 60
  envs:
    - PG_HOST
    - PG_PASSWORD
    - PG_USER
    - PG_DATABASE
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_BUCKET_NAME
    - AWS_HOST
    - AWS_PORT

pgrestore:
  name: pg-restore
  image: cr.yandex/crpn9ikb6hp5v19o9957/pgrestore
  version: 15
  envs:
    - PG_HOST
    - PG_PASSWORD
    - PG_USER
    - PG_DATABASE
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_BUCKET_NAME
    - AWS_HOST
    - AWS_PORT

app:
  name: inf-app
  image: cr.yandex/crpn9ikb6hp5v19o9957/inf-frontend-dev
  version: 810fa8
  components: frontend
  port: 3000
  replicas: 1
  requests:
    cpu: "400m"
    memory: "400Mi"
  limits:
    cpu: "400m"
    memory: "400Mi"
  envs:
    - EXTERNAL_CATALOG_SERVER_URL
    - API_SERVER_URL

api:
  name: inf-api
  image: cr.yandex/crpn9ikb6hp5v19o9957/inf-backend-dev
  version: 6ade93
  components: backend
  port: 2348
  replicas: 1
  requests:
    cpu: "400m"
    memory: "400Mi"
  limits:
    cpu: "400m"
    memory: "400Mi"
  envs:
    - CLIENT_URL
    - DB_PORT
    - DB_HOST
    - REDIS_URL

postgres:
  name: postgres
  image: postgres
  version: 14
  replicas: 1
  components: postgres
  port: 5432
  requests:
    cpu: "750m"
    memory: "7500Mi"
  limits:
    cpu: "750m"
    memory: "750Mi"
  envs:
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD

redis:
  name: redis
  image: redis
  version: 7.0.7
  replicas: 1
  components: redis
  port: 6379
  requests:
    cpu: "200m"
    memory: "250Mi"
  limits:
    cpu: "200m"
    memory: "250Mi"
    
database:
  db: inf
  user: postgres
  password: postgres

vault:
  secret_id_app: "ef53792c-b040-d1a7-ce39-1f778bd9a135"
  secret_id_api: "d53d52fc-c53f-0d8f-9850-ecceeadf8c97"
  secret_id_postgres: "9c06c6df-7d5a-6d8a-9eaf-72f936af806d"
  secret_id_s3: "944515c5-9c30-e276-63e4-72dfcc31dcbc"
  all_role_id: "7169e64c-b0db-957d-5fe7-79fce162f194"
  server_ip: "http://10.96.151.87:8200"

namespace:
  istio: "inf-application-istio"