pgdumper:
  name: pg-dumper
  image: cr.yandex/crpn9ikb6hp5v19o9957/pgdumper
  version: 60
  envs:
    - PG_HOST
    - PG_PASSWORD
    - PG_USER
    - PG_DATABASE
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_BUCKET_NAME
    - AWS_HOST
    - AWS_PORT

pgrestore:
  name: pg-restore
  image: cr.yandex/crpn9ikb6hp5v19o9957/pgrestore
  version: 15
  envs:
    - PG_HOST
    - PG_PASSWORD
    - PG_USER
    - PG_DATABASE
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_BUCKET_NAME
    - AWS_HOST
    - AWS_PORT

app:
  name: inf-app
  image: cr.yandex/crpn9ikb6hp5v19o9957/inf-frontend-dev
  version: 810fa8
  components: frontend
  port: 3000
  replicas: 1
  requests:
    cpu: "400m"
    memory: "400Mi"
  limits:
    cpu: "400m"
    memory: "400Mi"
  envs:
    - EXTERNAL_CATALOG_SERVER_URL
    - API_SERVER_URL

api:
  name: inf-api
  image: cr.yandex/crpn9ikb6hp5v19o9957/inf-backend-dev
  version: 6ade93
  components: backend
  port: 2348
  replicas: 1
  requests:
    cpu: "400m"
    memory: "400Mi"
  limits:
    cpu: "400m"
    memory: "400Mi"
  envs:
    - CLIENT_URL
    - DB_PORT
    - DB_HOST
    - REDIS_URL

postgres:
  name: postgres
  image: postgres
  version: 14
  replicas: 1
  components: postgres
  port: 5432
  requests:
    cpu: "750m"
    memory: "7500Mi"
  limits:
    cpu: "750m"
    memory: "750Mi"
  envs:
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD

redis:
  name: redis
  image: redis
  version: 7.0.7
  replicas: 1
  components: redis
  port: 6379
  requests:
    cpu: "200m"
    memory: "250Mi"
  limits:
    cpu: "200m"
    memory: "250Mi"
    
database:
  db: inf
  user: postgres
  password: postgres

vault:
  secret_id_app: "e32d94d0-b58e-68b9-3f01-150b5f679289"
  secret_id_api: "ea321867-c330-8fd7-4466-b77b758a1981"
  secret_id_postgres: "4f088be1-16ae-0e12-247e-f30087f8c5a8"
  secret_id_s3: "4ecdfd05-43ea-1c1b-79c3-c009b7f771d7"
  all_role_id: "b259d78d-ddc6-fac3-d917-f0e42f3360f4"
  server_ip: "http://10.96.194.117:8200"


namespace:
  istio: "inf-application-istio"