apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name }}-secret
type: Opaque
data:
  DB_PORT: NTQzMg==
  DB_HOST: cG9zdGdyZXMtY2x1c3Rlcmlw
  CLIENT_URL: c2hvcnQtYXBwLWNsdXN0ZXJpcDozMDAw
  REDIS_URL: cmVkaXMtY2x1c3RlcmlwOjYzNzk=