apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
type: Opaque
data:
  API_SERVER_URL: aHR0cDovL2luZmluaXR1bS50ZXN0L2FwaQ==
  EXTERNAL_CATALOG_SERVER_URL: aHR0cDovL2luZmluaXR1bS50ZXN0L2FwaQ==