apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-postgres
spec:
  provider:
    vault:
      server: "http://10.96.229.1:8200" # Указываем адрес Hashicorp Vault.
      path: "secret" # Только по этому пути может ходить ClusterSecretStore в Hashicorp Vault.
      version: "v2"
      auth:
        # AppRole аутентифицируется в Vault с помощью механизма
        # аутентификации AppRole https://www.vaultproject.io/docs/auth/approle.
        appRole:
          # Путь, по которому подключен сервер аутентификации AppRole.
          path: "approle"
          # Идентификатор роли, настроенный в серверной части проверки подлинности AppRole.
          roleId: "7213acfc-ff92-1167-c7d8-f587a7039b82" # Значение берем из  вывода `terraform output role_id`.
          secretRef:
            name: "vault-secret-postgres" # Название секрета Kubernetes, содержащий секретный идентификатор AppRole.
            key: "secret-id" # Секретный идентификатор AppRole.
            # namespace: external-secrets # Пространство имен, в котором вы можете найти секретный идентификатор для данной AppRole.