apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-api
spec:
  provider:
    vault:
      server: "http://10.96.228.161:8200" # Указываем адрес Hashicorp Vault.
      path: "secret" # Только по этому пути может ходить ClusterSecretStore в Hashicorp Vault.
      version: "v2"
      auth:
        # AppRole аутентифицируется в Vault с помощью механизма
        # аутентификации AppRole https://www.vaultproject.io/docs/auth/approle.
        appRole:
          # Путь, по которому подключен сервер аутентификации AppRole.
          path: "approle"
          # Идентификатор роли, настроенный в серверной части проверки подлинности AppRole.
          roleId: "6ca86133-4d93-206a-c0f3-c6cccd250bd6" # Значение берем из  вывода `terraform output role_id`.
          secretRef:
            name: "vault-secret-api" # Название секрета Kubernetes, содержащий секретный идентификатор AppRole.
            key: "secret-id" # Секретный идентификатор AppRole.
            # namespace: external-secrets # Пространство имен, в котором вы можете найти секретный идентификатор для данной AppRole.