apiVersion: v1
stringData:
  secret-id: "dec8a84d-0648-2649-ae26-f4b5787a9440" # Значение берем из  вывода `terraform output secret_id`.
kind: Secret
metadata:
  name: vault-secret-app # Название секрета Kubernetes, содержащий секретный идентификатор AppRole.
  # namespace: external-secrets # Пространство имен, в котором вы можете найти секретный идентификатор для данной AppRole.
type: Opaque