apiVersion: v1
stringData:
  secret-id: "be2ff9c2-75ce-e4dd-e659-73f35b12ecf3" # Значение берем из  вывода `terraform output secret_id`.
kind: Secret
metadata:
  name: vault-secret-api # Название секрета Kubernetes, содержащий секретный идентификатор AppRole.
  # namespace: external-secrets # Пространство имен, в котором вы можете найти секретный идентификатор для данной AppRole.
type: Opaque