apiVersion: v1
stringData:
  secret-id: "7a873ce7-14ca-24dc-a1fa-fb681d204771" # Значение берем из  вывода `terraform output secret_id`.
kind: Secret
metadata:
  name: vault-secret-s3 # Название секрета Kubernetes, содержащий секретный идентификатор AppRole.
  # namespace: external-secrets # Пространство имен, в котором вы можете найти секретный идентификатор для данной AppRole.
type: Opaque