apiVersion: v1
stringData:
  secret-id: "0c3a2ccb-f5a1-a525-2593-df406c16f5a6" # Значение берем из  вывода `terraform output secret_id`.
kind: Secret
metadata:
  name: vault-secret-s3 # Название секрета Kubernetes, содержащий секретный идентификатор AppRole.
  # namespace: external-secrets # Пространство имен, в котором вы можете найти секретный идентификатор для данной AppRole.
type: Opaque