apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      components: {{ .Values.app.components }}
  template:
    metadata:
      labels:
        components: {{ .Values.app.components }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.version }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
              {{- range .Values.app.envs }}
              {{- $data := dict "name" $.Values.app.name "env" . }}
              {{- include "env.template" $data | indent 14 }}
              {{- end }}
          resources:
            limits: {{ .Values.app.limits | toYaml | nindent 15 }}
      nodeSelector:
        typeNode: stateless