apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: k8s-secret-app # the target k8s secret name
  data:
  - secretKey: API_SERVER_URL # the target k8s secret key
    remoteRef:
      key: e6qmm0njobcriadtdktr # ID of lockbox-secret
      property: API_SERVER_URL # (optional) payload entry key of lockbox-secret
  - secretKey: EXTERNAL_CATALOG_SERVER_URL # the target k8s secret key
    remoteRef:
      key: e6qmm0njobcriadtdktr # ID of lockbox-secret
      property: EXTERNAL_CATALOG_SERVER_URL # (optional) payload entry key of lockbox-secret