apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-s3
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: k8s-secret-s3 # the target k8s secret name
  data:
  - secretKey: PG_HOST # the target k8s secret key
    remoteRef:
      key: e6q0q6n295r7b37e82s1 # ID of lockbox-secret
      property: PG_HOST # (optional) payload entry key of lockbox-secret
  - secretKey: PG_PASSWORD # the target k8s secret key
    remoteRef:
      key: e6q0q6n295r7b37e82s1 # ID of lockbox-secret
      property: PG_PASSWORD # (optional) payload entry key of lockbox-secret
  - secretKey: PG_USER # the target k8s secret key
    remoteRef:
      key: e6q0q6n295r7b37e82s1 # ID of lockbox-secret
      property: PG_USER # (optional) payload entry key of lockbox-secret
  - secretKey: PG_DATABASE # the target k8s secret key
    remoteRef:
      key: e6q0q6n295r7b37e82s1 # ID of lockbox-secret
      property: PG_DATABASE # (optional) payload entry key of lockbox-secret
  - secretKey: AWS_ACCESS_KEY_ID # the target k8s secret key
    remoteRef:
      key: e6q0q6n295r7b37e82s1 # ID of lockbox-secret
      property: AWS_ACCESS_KEY_ID # (optional) payload entry key of lockbox-secret
  - secretKey: AWS_SECRET_ACCESS_KEY # the target k8s secret key
    remoteRef:
      key: e6q0q6n295r7b37e82s1 # ID of lockbox-secret
      property: AWS_SECRET_ACCESS_KEY # (optional) payload entry key of lockbox-secret
  - secretKey: AWS_BUCKET_NAME # the target k8s secret key
    remoteRef:
      key: e6q0q6n295r7b37e82s1 # ID of lockbox-secret
      property: AWS_BUCKET_NAME # (optional) payload entry key of lockbox-secret
  - secretKey: AWS_HOST # the target k8s secret key
    remoteRef:
      key: e6q0q6n295r7b37e82s1 # ID of lockbox-secret
      property: AWS_HOST # (optional) payload entry key of lockbox-secret
  - secretKey: AWS_PORT # the target k8s secret key
    remoteRef:
      key: e6q0q6n295r7b37e82s1 # ID of lockbox-secret
      property: AWS_PORT # (optional) payload entry key of lockbox-secret
    