apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: k8s-secret-postgres # the target k8s secret name
  data:
  - secretKey: POSTGRES_DB # the target k8s secret key
    remoteRef:
      key: e6q44tvr4jhibe3lua5p # ID of lockbox-secret
      property: POSTGRES_DB # (optional) payload entry key of lockbox-secret
  - secretKey: POSTGRES_USER # the target k8s secret key
    remoteRef:
      key: e6q44tvr4jhibe3lua5p # ID of lockbox-secret
      property: POSTGRES_USER # (optional) payload entry key of lockbox-secret
  - secretKey: POSTGRES_PASSWORD # the target k8s secret key
    remoteRef:
      key: e6q44tvr4jhibe3lua5p # ID of lockbox-secret
      property: POSTGRES_PASSWORD # (optional) payload entry key of lockbox-secret