apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: k8s-secret-api # the target k8s secret name
  data:
  - secretKey: DB_PORT # the target k8s secret key
    remoteRef:
      key: e6qfvtog1g9gg72spag7 # ID of lockbox-secret
      property: DB_PORT # (optional) payload entry key of lockbox-secret
  - secretKey: DB_HOST # the target k8s secret key
    remoteRef:
      key: e6qfvtog1g9gg72spag7 # ID of lockbox-secret
      property: DB_HOST # (optional) payload entry key of lockbox-secret
  - secretKey: CLIENT_URL # the target k8s secret key
    remoteRef:
      key: e6qfvtog1g9gg72spag7 # ID of lockbox-secret
      property: CLIENT_URL # (optional) payload entry key of lockbox-secret
  - secretKey: REDIS_URL # the target k8s secret key
    remoteRef:
      key: e6qfvtog1g9gg72spag7 # ID of lockbox-secret
      property: REDIS_URL # (optional) payload entry key of lockbox-secret