global:
  pgdumper:
    name: pg-dumper
    image: cr.yandex/crpn9ikb6hp5v19o9957/pgdumper
    version: 60
    envs:
      - PG_HOST
      - PG_PASSWORD
      - PG_USER
      - PG_DATABASE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET_NAME
      - AWS_HOST
      - AWS_PORT
  pgrestore:
    name: pg-restore
    image: cr.yandex/crpn9ikb6hp5v19o9957/pgrestore
    version: 15
    envs:
      - PG_HOST
      - PG_PASSWORD
      - PG_USER
      - PG_DATABASE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET_NAME
      - AWS_HOST
      - AWS_PORT
  app:
    name: inf-app
    image: cr.yandex/crpn9ikb6hp5v19o9957/inf-frontend-dev
    version: 810fa8
    components: frontend
    port: 3000
    replicas: 1
    requests:
      cpu: "250m"
      memory: "250Mi"
    limits:
      cpu: "250m"
      memory: "250Mi"
    envs:
      - EXTERNAL_CATALOG_SERVER_URL
      - API_SERVER_URL
  api:
    name: inf-api
    image: cr.yandex/crpn9ikb6hp5v19o9957/inf-backend-dev
    version: 6ade93
    components: backend
    port: 2348
    replicas: 1
    requests:
      cpu: "500m"
      memory: "350Mi"
    limits:
      cpu: "500m"
      memory: "350Mi"
    envs:
      - CLIENT_URL
      - DB_PORT
      - DB_HOST
      - REDIS_URL
  postgres:
    name: postgres
    image: postgres
    version: 14
    replicas: 1
    components: postgres
    port: 5432
    requests:
      cpu: "1000m"
      memory: "2000Mi"
    limits:
      cpu: "1000m"
      memory: "2000Mi"
    envs:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  redis:
    name: redis
    image: redis
    version: 7.0.7
    replicas: 1
    components: redis
    port: 6379
    requests:
      cpu: "200m"
      memory: "250Mi"
    limits:
      cpu: "200m"
      memory: "250Mi"
  database:
    db: inf
    user: postgres
    password: postgres
  vault:
    secret_id_postgres: "0b53e1b6-ffc1-061d-46ca-150c801d515e"
    secret_id_api: "91a40689-951f-9ef9-106a-130fb0a5d419"
    secret_id_app: "2e795ded-341d-2841-aa7a-aed0d0a81455"
    secret_id_s3: "0f211ce6-3271-13f4-28a4-ac1d35d3c10b"
    all_role_id: "ed0f8887-029b-d21d-2607-348a867807c4"
    server_ip: "http://10.96.171.186:8200"
