apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.global.postgres.name }}-deployment"
spec:
  replicas: {{ .Values.global.postgres.replicas }}
  selector:
    matchLabels:
      components: {{ .Values.global.postgres.components }}
  template:
    metadata:
      labels:
        components: {{ .Values.global.postgres.components }}
    spec:
      containers:
        - name: {{ .Values.global.postgres.name }}
          image: "{{ .Values.global.postgres.image }}:{{ .Values.global.postgres.version }}"
          ports:
            - containerPort: {{ .Values.global.postgres.port }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: "postgres-secret"
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: "postgres-secret"
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "postgres-secret"
                  key: POSTGRES_PASSWORD
          resources:
            limits: {{ .Values.global.postgres.limits | toYaml | nindent 14 }}
          volumeMounts:
            - name: "{{ .Values.global.postgres.name }}-data"
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      nodeSelector:
        typeNode: statefull
      volumes:
        - name: "{{ .Values.global.postgres.name }}-data"
          persistentVolumeClaim:
            claimName: "{{ .Values.global.postgres.name }}-pvc"