apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.global.postgres.name }}-clusterip"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.postgres.port }}
      protocol: TCP
  selector:
    components: {{ .Values.global.postgres.components }}