apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.global.api.name }}-clusterip"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.api.port }}
      protocol: TCP
  selector:
    components: {{ .Values.global.api.components }}