apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-api
  annotations:
      nginx.ingress.kubernetes.io/base-url: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: infinitum.test
    http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: "{{ .Values.global.api.name }}-clusterip"
            port:
              number: {{ .Values.global.api.port }}
      - pathType: Prefix
        path: "/api/v2"
        backend:
          service:
            name: "{{ .Values.global.api.name }}-clusterip"
            port:
              number: {{ .Values.global.api.port }}